name: React CI/CD Pipeline

on:
  push:
    branches:
      - main  # Trigger deployment on push to the 'main' branch

jobs:
  build:
    runs-on: ubuntu-latest  # Run on Ubuntu environment

    steps:
    - name: Checkout code
      uses: actions/checkout@v2  # Checkout the repository

    - name: Set up Node.js
      uses: actions/setup-node@v2
      with:
        node-version: '14'  # Use Node.js 14

    - name: Install dependencies
      run: npm install  # Install dependencies

    - name: Run tests
      run: npm test -- --coverage  # Run tests with coverage (optional)

    - name: Build React app
      run: npm run build  # Build the app for production

    - name: Deploy to GitHub Pages
      if: github.ref == 'refs/heads/main'  # Only deploy from the 'main' branch
      run: |
        npm install gh-pages --save-dev  # Install gh-pages
        npm run deploy  # Deploy to GitHub Pages
